#!/usr/bin/env python3
"""Independent, arbitrary-precision Python reference; no third-party modules."""
import json
from pathlib import Path

MASK = (1 << 64) - 1

def hash_u64(value: int, seed: int = 0) -> int:
    """Hash a 64-bit integer with the SplitMix64 finalizer

    Args:
        value: Integer to hash
        seed: Integer offset applied before mixing

    Returns:
        The 64-bit hash

    Raises:
        TypeError: If an argument is not an integer
    """
    x = (value + seed + 0x9E3779B97F4A7C15) & MASK
    x = ((x ^ (x >> 30)) * 0xBF58476D1CE4E5B9) & MASK
    x = ((x ^ (x >> 27)) * 0x94D049BB133111EB) & MASK
    return x ^ (x >> 31)

if __name__ == '__main__':
    values = [0, 1, 2, 123, 2**32-1, 2**32, 2**63, MASK, 0x0123456789ABCDEF]
    seeds = [0, 1, 42, MASK, 2**63, 0x123456789ABCDEF0]
    records = [dict(input=x, seed=s, output=hash_u64(x,s)) for s in seeds for x in values]
    root = Path(__file__).resolve().parents[1]
    (root/'tests/vectors.json').write_text(json.dumps(records,indent=2)+'\n')
    lines = ['// Generated by tools/reference_vectors.py; checked by test.cpp.',
             '#pragma once', '#include <cstdint>',
             'struct vector_case { std::uint64_t input, seed, output; };',
             'inline constexpr vector_case known_vectors[] = {']
    lines += ['    {UINT64_C(0x%016x), UINT64_C(0x%016x), UINT64_C(0x%016x)},' %
              (r['input'],r['seed'],r['output']) for r in records]
    lines += ['};', '']
    (root/'tests/vectors.hpp').write_text('\n'.join(lines))
    print(f'Wrote {len(records)} cross-language vectors.')
